///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package relations

import (
	"fmt"
	"time"

	"github.com/xinliangnote/go-gin-api/internal/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *Relations {
	return new(Relations)
}

func NewQueryBuilder() *relationsQueryBuilder {
	return new(relationsQueryBuilder)
}

func (t *Relations) Create(db *gorm.DB) (id int32, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type relationsQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *relationsQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *relationsQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&Relations{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *relationsQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&Relations{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *relationsQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&Relations{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *relationsQueryBuilder) First(db *gorm.DB) (*Relations, error) {
	ret := &Relations{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *relationsQueryBuilder) QueryOne(db *gorm.DB) (*Relations, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *relationsQueryBuilder) QueryAll(db *gorm.DB) ([]*Relations, error) {
	var ret []*Relations
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *relationsQueryBuilder) Limit(limit int) *relationsQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *relationsQueryBuilder) Offset(offset int) *relationsQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *relationsQueryBuilder) WhereId(p mysql.Predicate, value int32) *relationsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *relationsQueryBuilder) WhereIdIn(value []int32) *relationsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *relationsQueryBuilder) WhereIdNotIn(value []int32) *relationsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *relationsQueryBuilder) OrderById(asc bool) *relationsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *relationsQueryBuilder) WhereEventId(p mysql.Predicate, value int32) *relationsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "event_id", p),
		value,
	})
	return qb
}

func (qb *relationsQueryBuilder) WhereEventIdIn(value []int32) *relationsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "event_id", "IN"),
		value,
	})
	return qb
}

func (qb *relationsQueryBuilder) WhereEventIdNotIn(value []int32) *relationsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "event_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *relationsQueryBuilder) OrderByEventId(asc bool) *relationsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "event_id "+order)
	return qb
}

func (qb *relationsQueryBuilder) WherePlaceId(p mysql.Predicate, value int32) *relationsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "place_id", p),
		value,
	})
	return qb
}

func (qb *relationsQueryBuilder) WherePlaceIdIn(value []int32) *relationsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "place_id", "IN"),
		value,
	})
	return qb
}

func (qb *relationsQueryBuilder) WherePlaceIdNotIn(value []int32) *relationsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "place_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *relationsQueryBuilder) OrderByPlaceId(asc bool) *relationsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "place_id "+order)
	return qb
}

func (qb *relationsQueryBuilder) WherePersonId(p mysql.Predicate, value int32) *relationsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "person_id", p),
		value,
	})
	return qb
}

func (qb *relationsQueryBuilder) WherePersonIdIn(value []int32) *relationsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "person_id", "IN"),
		value,
	})
	return qb
}

func (qb *relationsQueryBuilder) WherePersonIdNotIn(value []int32) *relationsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "person_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *relationsQueryBuilder) OrderByPersonId(asc bool) *relationsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "person_id "+order)
	return qb
}

func (qb *relationsQueryBuilder) WhereCreatetime(p mysql.Predicate, value time.Time) *relationsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "createtime", p),
		value,
	})
	return qb
}

func (qb *relationsQueryBuilder) WhereCreatetimeIn(value []time.Time) *relationsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "createtime", "IN"),
		value,
	})
	return qb
}

func (qb *relationsQueryBuilder) WhereCreatetimeNotIn(value []time.Time) *relationsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "createtime", "NOT IN"),
		value,
	})
	return qb
}

func (qb *relationsQueryBuilder) OrderByCreatetime(asc bool) *relationsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "createtime "+order)
	return qb
}

func (qb *relationsQueryBuilder) WhereUpdatetime(p mysql.Predicate, value time.Time) *relationsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updatetime", p),
		value,
	})
	return qb
}

func (qb *relationsQueryBuilder) WhereUpdatetimeIn(value []time.Time) *relationsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updatetime", "IN"),
		value,
	})
	return qb
}

func (qb *relationsQueryBuilder) WhereUpdatetimeNotIn(value []time.Time) *relationsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updatetime", "NOT IN"),
		value,
	})
	return qb
}

func (qb *relationsQueryBuilder) OrderByUpdatetime(asc bool) *relationsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "updatetime "+order)
	return qb
}
